// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PollResult reports the outcome of polling a single filter.
 */
export class PollResult {
    /**
     * Creates a new PollResult instance.
     * @param {Partial<PollResult>} [$$source = {}] - The source object to create the PollResult.
     */
    constructor($$source = {}) {
        if (!("FilterID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FilterID"] = "";
        }
        if (!("FilterName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FilterName"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("NewJobs" in $$source)) {
            /**
             * How many new jobs were stored
             * @member
             * @type {number}
             */
            this["NewJobs"] = 0;
        }
        if (!("Skipped" in $$source)) {
            /**
             * How many duplicates were skipped
             * @member
             * @type {number}
             */
            this["Skipped"] = 0;
        }
        if (!("Err" in $$source)) {
            /**
             * Non-nil if the filter failed entirely
             * @member
             * @type {any}
             */
            this["Err"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PollResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PollResult(/** @type {Partial<PollResult>} */($$parsedSource));
    }
}
