// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Job represents a discovered job posting stored in the database.
 * Jobs are found by adapters during polling and deduplicated via the
 * UNIQUE(source, source_id) constraint.
 */
export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * UUID primary key
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * Which adapter found this, e.g. "reed_uk"
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("SourceID" in $$source)) {
            /**
             * External ID / URL hash for deduplication
             * @member
             * @type {string}
             */
            this["SourceID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * Job title
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Company" in $$source)) {
            /**
             * Company name
             * @member
             * @type {string}
             */
            this["Company"] = "";
        }
        if (!("Location" in $$source)) {
            /**
             * Job location
             * @member
             * @type {string}
             */
            this["Location"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * Full job description text
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * Link to original posting
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("PostedAt" in $$source)) {
            /**
             * When the job was posted (from source), nullable
             * @member
             * @type {time$0.Time | null}
             */
            this["PostedAt"] = null;
        }
        if (!("DiscoveredAt" in $$source)) {
            /**
             * When Hamster Wheel found this job
             * @member
             * @type {time$0.Time}
             */
            this["DiscoveredAt"] = null;
        }
        if (!("FilterID" in $$source)) {
            /**
             * Which search filter discovered this, nullable
             * @member
             * @type {string | null}
             */
            this["FilterID"] = null;
        }
        if (!("IsFavorite" in $$source)) {
            /**
             * Whether user marked this job as favorite
             * @member
             * @type {boolean}
             */
            this["IsFavorite"] = false;
        }
        if (!("MatchStatus" in $$source)) {
            /**
             * Current matching status (pending/processing/matched/failed), empty if unavailable
             * @member
             * @type {string}
             */
            this["MatchStatus"] = "";
        }
        if (!("MatchScore" in $$source)) {
            /**
             * Latest match score (0.0-1.0)
             * @member
             * @type {number}
             */
            this["MatchScore"] = 0;
        }
        if (!("MatchSummary" in $$source)) {
            /**
             * Latest match summary
             * @member
             * @type {string}
             */
            this["MatchSummary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}

/**
 * SearchFilter represents a saved search configuration that the scheduler
 * uses to poll a job source. Each filter maps to one adapter (e.g., "reed_uk")
 * and contains the keywords + location the user wants to monitor.
 */
export class SearchFilter {
    /**
     * Creates a new SearchFilter instance.
     * @param {Partial<SearchFilter>} [$$source = {}] - The source object to create the SearchFilter.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * UUID primary key
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * User-given name, e.g. "Backend London"
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Keywords" in $$source)) {
            /**
             * Search keywords
             * @member
             * @type {string}
             */
            this["Keywords"] = "";
        }
        if (!("Location" in $$source)) {
            /**
             * Location string
             * @member
             * @type {string}
             */
            this["Location"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * Adapter identifier, e.g. "reed_uk"
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Enabled" in $$source)) {
            /**
             * Whether the scheduler should poll this filter
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * When the filter was created
             * @member
             * @type {time$0.Time}
             */
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * When the filter was last modified
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchFilter(/** @type {Partial<SearchFilter>} */($$parsedSource));
    }
}
