// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the main Wails service. All exported methods are
 * automatically exposed to the React frontend via Wails bindings.
 * 
 * In Wails v3, services are plain Go structs registered with the app.
 * They optionally implement ServiceStartup/ServiceShutdown for lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "./internal/scheduler/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFilter creates a new search filter and returns its ID.
 * @param {string} name
 * @param {string} keywords
 * @param {string} location
 * @param {string} source
 * @returns {$CancellablePromise<string>}
 */
export function CreateFilter(name, keywords, location, source) {
    return $Call.ByID(167331448, name, keywords, location, source);
}

/**
 * DeleteFilter removes a search filter by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFilter(id) {
    return $Call.ByID(2127563399, id);
}

/**
 * DeleteJob removes a job by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJob(id) {
    return $Call.ByID(3963361868, id);
}

/**
 * GetFilter returns a single filter by ID, or nil if not found.
 * @param {string} id
 * @returns {$CancellablePromise<db$0.SearchFilter | null>}
 */
export function GetFilter(id) {
    return $Call.ByID(639797120, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetFilters returns all search filters.
 * @returns {$CancellablePromise<db$0.SearchFilter[]>}
 */
export function GetFilters() {
    return $Call.ByID(4217111433).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetJob returns a single job by ID, or nil if not found.
 * @param {string} id
 * @returns {$CancellablePromise<db$0.Job | null>}
 */
export function GetJob(id) {
    return $Call.ByID(1474257769, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetJobCount returns the total number of jobs in the database.
 * @returns {$CancellablePromise<number>}
 */
export function GetJobCount() {
    return $Call.ByID(2339114608);
}

/**
 * GetJobs returns jobs ordered by discovery date (newest first).
 * Pass limit=0 for all jobs.
 * @param {number} limit
 * @returns {$CancellablePromise<db$0.Job[]>}
 */
export function GetJobs(limit) {
    return $Call.ByID(1856569838, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetJobsByFilter returns jobs discovered through a specific filter.
 * @param {string} filterID
 * @returns {$CancellablePromise<db$0.Job[]>}
 */
export function GetJobsByFilter(filterID) {
    return $Call.ByID(2972035073, filterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetPollingStatus returns whether auto-polling is paused and when the next poll is due.
 * @returns {$CancellablePromise<$models.PollingStatus>}
 */
export function GetPollingStatus() {
    return $Call.ByID(927075235).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetReedAPIKey returns the stored Reed API key (empty if not set).
 * @returns {$CancellablePromise<string>}
 */
export function GetReedAPIKey() {
    return $Call.ByID(910041189);
}

/**
 * PollNow triggers an immediate poll cycle and returns the results.
 * @returns {$CancellablePromise<scheduler$0.PollResult[]>}
 */
export function PollNow() {
    return $Call.ByID(3753963293).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SetPollingPaused pauses or resumes auto-polling. Manual PollNow still works.
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPollingPaused(paused) {
    return $Call.ByID(1191974251, paused);
}

/**
 * SetReedAPIKey saves the Reed API key and updates the adapter immediately.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetReedAPIKey(key) {
    return $Call.ByID(1243423177, key);
}

/**
 * UpdateFilter updates an existing search filter.
 * @param {string} id
 * @param {string} name
 * @param {string} keywords
 * @param {string} location
 * @param {string} source
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFilter(id, name, keywords, location, source, enabled) {
    return $Call.ByID(3745716397, id, name, keywords, location, source, enabled);
}

// Private type creation functions
const $$createType0 = db$0.SearchFilter.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = db$0.Job.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType3);
const $$createType6 = $models.PollingStatus.createFrom;
const $$createType7 = scheduler$0.PollResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
