// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilterService handles search filter operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";

/**
 * CreateFilter creates a new search filter and returns its ID.
 * @param {string} name
 * @param {string} keywords
 * @param {string} location
 * @param {string} source
 * @returns {$CancellablePromise<string>}
 */
export function CreateFilter(name, keywords, location, source) {
    return $Call.ByID(1316581277, name, keywords, location, source);
}

/**
 * DeleteFilter removes a search filter by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFilter(id) {
    return $Call.ByID(1084638706, id);
}

/**
 * GetFilter returns a single filter by ID, or nil if not found.
 * @param {string} id
 * @returns {$CancellablePromise<db$0.SearchFilter | null>}
 */
export function GetFilter(id) {
    return $Call.ByID(1236785407, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetFilters returns all search filters.
 * @returns {$CancellablePromise<db$0.SearchFilter[]>}
 */
export function GetFilters() {
    return $Call.ByID(2557076580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateFilter updates an existing search filter.
 * @param {string} id
 * @param {string} name
 * @param {string} keywords
 * @param {string} location
 * @param {string} source
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFilter(id, name, keywords, location, source, enabled) {
    return $Call.ByID(831319228, id, name, keywords, location, source, enabled);
}

// Private type creation functions
const $$createType0 = db$0.SearchFilter.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
