// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JobService handles job-related operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";

/**
 * DeleteJob removes a job by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteJob(id) {
    return $Call.ByID(1245916576, id);
}

/**
 * GetJob returns a single job by ID, or nil if not found.
 * @param {string} id
 * @returns {$CancellablePromise<db$0.Job | null>}
 */
export function GetJob(id) {
    return $Call.ByID(3935635757, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetJobCount returns the total number of jobs in the database.
 * @returns {$CancellablePromise<number>}
 */
export function GetJobCount() {
    return $Call.ByID(2713019372);
}

/**
 * GetJobs returns jobs ordered by discovery date (newest first).
 * Pass limit=0 for all jobs.
 * @param {number} limit
 * @returns {$CancellablePromise<db$0.Job[]>}
 */
export function GetJobs(limit) {
    return $Call.ByID(2795355898, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetJobsByFilter returns jobs discovered through a specific filter.
 * @param {string} filterID
 * @returns {$CancellablePromise<db$0.Job[]>}
 */
export function GetJobsByFilter(filterID) {
    return $Call.ByID(2465026157, filterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = db$0.Job.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
