// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PollFilterResult reports the outcome of polling one filter.
 */
export class PollFilterResult {
    /**
     * Creates a new PollFilterResult instance.
     * @param {Partial<PollFilterResult>} [$$source = {}] - The source object to create the PollFilterResult.
     */
    constructor($$source = {}) {
        if (!("filterID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filterID"] = "";
        }
        if (!("filterName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filterName"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("newJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newJobs"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollFilterResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PollFilterResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PollFilterResult(/** @type {Partial<PollFilterResult>} */($$parsedSource));
    }
}

/**
 * PollRunResult reports one manual poll run and where its diagnostics were stored.
 */
export class PollRunResult {
    /**
     * Creates a new PollRunResult instance.
     * @param {Partial<PollRunResult>} [$$source = {}] - The source object to create the PollRunResult.
     */
    constructor($$source = {}) {
        if (!("runID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runID"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * RFC3339 timestamp
             * @member
             * @type {string}
             */
            this["startedAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            /**
             * RFC3339 timestamp
             * @member
             * @type {string}
             */
            this["completedAt"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("totalFilters" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalFilters"] = 0;
        }
        if (!("failedFilters" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedFilters"] = 0;
        }
        if (!("newJobs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newJobs"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cycleError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["diagnosticsPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["diagnosticsError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PollFilterResult[] | undefined}
             */
            this["filters"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PollRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField11_0($$parsedSource["filters"]);
        }
        return new PollRunResult(/** @type {Partial<PollRunResult>} */($$parsedSource));
    }
}

/**
 * PollingStatus represents the current state of auto-polling.
 */
export class PollingStatus {
    /**
     * Creates a new PollingStatus instance.
     * @param {Partial<PollingStatus>} [$$source = {}] - The source object to create the PollingStatus.
     */
    constructor($$source = {}) {
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("isPolling" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPolling"] = false;
        }
        if (!("nextPollAt" in $$source)) {
            /**
             * RFC3339 timestamp, empty if not scheduled
             * @member
             * @type {string}
             */
            this["nextPollAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollingStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PollingStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PollingStatus(/** @type {Partial<PollingStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PollFilterResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
