// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PollingStatus represents the current state of auto-polling.
 */
export class PollingStatus {
    /**
     * Creates a new PollingStatus instance.
     * @param {Partial<PollingStatus>} [$$source = {}] - The source object to create the PollingStatus.
     */
    constructor($$source = {}) {
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("nextPollAt" in $$source)) {
            /**
             * RFC3339 timestamp, empty if not scheduled
             * @member
             * @type {string}
             */
            this["nextPollAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollingStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PollingStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PollingStatus(/** @type {Partial<PollingStatus>} */($$parsedSource));
    }
}
