// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PollingService handles job polling and scheduler control operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "./internal/scheduler/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetPollingStatus returns whether auto-polling is paused and when the next poll is due.
 * @returns {$CancellablePromise<$models.PollingStatus>}
 */
export function GetPollingStatus() {
    return $Call.ByID(222512135).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PollNow triggers an immediate poll cycle and returns the results.
 * @returns {$CancellablePromise<scheduler$0.PollResult[]>}
 */
export function PollNow() {
    return $Call.ByID(2173790801).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetPollingPaused pauses or resumes auto-polling. Manual PollNow still works.
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPollingPaused(paused) {
    return $Call.ByID(1316509351, paused);
}

// Private type creation functions
const $$createType0 = $models.PollingStatus.createFrom;
const $$createType1 = scheduler$0.PollResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
