// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PollingService handles job polling and scheduler control operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetPollingIntervalMinutes returns the scheduler polling interval in minutes.
 * @returns {$CancellablePromise<number>}
 */
export function GetPollingIntervalMinutes() {
    return $Call.ByID(3495258769);
}

/**
 * GetPollingStatus returns whether auto-polling is paused and when the next poll is due.
 * @returns {$CancellablePromise<$models.PollingStatus>}
 */
export function GetPollingStatus() {
    return $Call.ByID(222512135).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PollNow triggers an immediate poll cycle and returns structured run metadata.
 * 
 * Poll-cycle failures are reported in CycleError while preserving diagnostics.
 * The call only returns a transport error if the runtime itself fails.
 * @returns {$CancellablePromise<$models.PollRunResult>}
 */
export function PollNow() {
    return $Call.ByID(2173790801).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SavePollReport writes a user-exported poll report to the selected file path.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SavePollReport(path, content) {
    return $Call.ByID(2725635384, path, content);
}

/**
 * SetPollingIntervalMinutes updates the scheduler polling interval.
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function SetPollingIntervalMinutes(minutes) {
    return $Call.ByID(367355317, minutes);
}

/**
 * SetPollingPaused pauses or resumes auto-polling. Manual PollNow still works.
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPollingPaused(paused) {
    return $Call.ByID(1316509351, paused);
}

// Private type creation functions
const $$createType0 = $models.PollingStatus.createFrom;
const $$createType1 = $models.PollRunResult.createFrom;
