// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService handles application settings operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetKeyboardShortcuts returns whether keyboard shortcuts are enabled ("true", "false", or "" if unset).
 * Empty string means default (enabled).
 * @returns {$CancellablePromise<string>}
 */
export function GetKeyboardShortcuts() {
    return $Call.ByID(961249936);
}

/**
 * GetReedAPIKey returns the stored Reed API key (empty if not set).
 * @returns {$CancellablePromise<string>}
 */
export function GetReedAPIKey() {
    return $Call.ByID(269058791);
}

/**
 * GetTheme returns the stored theme preference ("dark", "light", "system", or "" if unset).
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(1377976733);
}

/**
 * SetKeyboardShortcuts saves the keyboard shortcuts preference. Must be "true" or "false".
 * @param {string} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKeyboardShortcuts(enabled) {
    return $Call.ByID(248813052, enabled);
}

/**
 * SetReedAPIKey saves the Reed API key and updates the adapter immediately.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetReedAPIKey(key) {
    return $Call.ByID(528752499, key);
}

/**
 * SetTheme saves the theme preference. Must be "dark", "light", or "system".
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(466396097, theme);
}
