// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService handles application settings operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetReedAPIKey returns the stored Reed API key (empty if not set).
 * @returns {$CancellablePromise<string>}
 */
export function GetReedAPIKey() {
    return $Call.ByID(269058791);
}

/**
 * SetReedAPIKey saves the Reed API key and updates the adapter immediately.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetReedAPIKey(key) {
    return $Call.ByID(528752499, key);
}
