// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService handles application settings operations exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localruntime$0 from "./internal/localruntime/models.js";

/**
 * ClearOpenAIAPIKey removes the stored OpenAI API key.
 * @returns {$CancellablePromise<void>}
 */
export function ClearOpenAIAPIKey() {
    return $Call.ByID(122384820);
}

/**
 * ClearReedAPIKey removes the stored Reed API key and clears the active adapter key.
 * @returns {$CancellablePromise<void>}
 */
export function ClearReedAPIKey() {
    return $Call.ByID(2946820606);
}

/**
 * GetAutoMatchEnabled returns whether new jobs should be auto-queued for matching.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoMatchEnabled() {
    return $Call.ByID(3937480409);
}

/**
 * GetAutoMatchLimit returns the maximum number of auto-queued matches per poll cycle.
 * A value of 0 means unlimited.
 * @returns {$CancellablePromise<number>}
 */
export function GetAutoMatchLimit() {
    return $Call.ByID(3208356667);
}

/**
 * GetCVPath returns the configured CV file path used for matching context.
 * @returns {$CancellablePromise<string>}
 */
export function GetCVPath() {
    return $Call.ByID(4209720150);
}

/**
 * GetKeyboardShortcuts returns whether keyboard shortcuts are enabled ("true", "false", or "" if unset).
 * Empty string means default (enabled).
 * @returns {$CancellablePromise<string>}
 */
export function GetKeyboardShortcuts() {
    return $Call.ByID(961249936);
}

/**
 * GetLLMBaseURL returns the configured provider base URL for OpenAI-compatible endpoints.
 * @returns {$CancellablePromise<string>}
 */
export function GetLLMBaseURL() {
    return $Call.ByID(4001770595);
}

/**
 * GetLLMMode returns the configured LLM operation mode.
 * Empty string falls back to default mode.
 * @returns {$CancellablePromise<string>}
 */
export function GetLLMMode() {
    return $Call.ByID(1309974512);
}

/**
 * GetLLMModel returns the configured LLM model.
 * Empty string falls back to default model.
 * @returns {$CancellablePromise<string>}
 */
export function GetLLMModel() {
    return $Call.ByID(2255962772);
}

/**
 * GetLLMProvider returns the stored LLM provider ("openai" or "heuristic_v1").
 * Empty string falls back to default provider.
 * @returns {$CancellablePromise<string>}
 */
export function GetLLMProvider() {
    return $Call.ByID(683130982);
}

/**
 * GetLocalRuntimeEngine returns the configured local runtime engine.
 * Empty string falls back to Ollama.
 * @returns {$CancellablePromise<string>}
 */
export function GetLocalRuntimeEngine() {
    return $Call.ByID(265433883);
}

/**
 * GetLocalRuntimeModel returns the configured local runtime model.
 * Empty string falls back to a default recommended model.
 * @returns {$CancellablePromise<string>}
 */
export function GetLocalRuntimeModel() {
    return $Call.ByID(379298746);
}

/**
 * GetLocalRuntimeModels returns recommended and installed local runtime models.
 * @returns {$CancellablePromise<localruntime$0.ModelCatalog>}
 */
export function GetLocalRuntimeModels() {
    return $Call.ByID(1610798443).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetLocalRuntimePullProgress returns in-flight local model pull progress.
 * @returns {$CancellablePromise<localruntime$0.PullProgress>}
 */
export function GetLocalRuntimePullProgress() {
    return $Call.ByID(1631203121).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLocalRuntimeStatus returns the current local runtime orchestration status.
 * @returns {$CancellablePromise<localruntime$0.Snapshot>}
 */
export function GetLocalRuntimeStatus() {
    return $Call.ByID(1586804687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTheme returns the stored theme preference ("dark", "light", "system", or "" if unset).
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(1377976733);
}

/**
 * HasOpenAIAPIKey reports whether an OpenAI API key is currently stored.
 * It never returns the secret to the frontend.
 * @returns {$CancellablePromise<boolean>}
 */
export function HasOpenAIAPIKey() {
    return $Call.ByID(4242933685);
}

/**
 * HasReedAPIKey reports whether a Reed API key is currently stored.
 * It never returns the secret to the frontend.
 * @returns {$CancellablePromise<boolean>}
 */
export function HasReedAPIKey() {
    return $Call.ByID(3464400619);
}

/**
 * PullLocalRuntimeModel pulls a model into local runtime storage.
 * @param {string} model
 * @returns {$CancellablePromise<localruntime$0.PullResult>}
 */
export function PullLocalRuntimeModel(model) {
    return $Call.ByID(666476807, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetAutoMatchEnabled saves whether new jobs should be auto-queued for matching.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoMatchEnabled(enabled) {
    return $Call.ByID(1926788837, enabled);
}

/**
 * SetAutoMatchLimit saves the maximum number of auto-queued matches per poll cycle.
 * A value of 0 means unlimited.
 * @param {number} limit
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoMatchLimit(limit) {
    return $Call.ByID(3478362263, limit);
}

/**
 * SetCVPath saves the CV file path used for matching context.
 * Empty value clears the stored path.
 * @param {string} cvPath
 * @returns {$CancellablePromise<void>}
 */
export function SetCVPath(cvPath) {
    return $Call.ByID(2451022818, cvPath);
}

/**
 * SetKeyboardShortcuts saves the keyboard shortcuts preference. Must be "true" or "false".
 * @param {string} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKeyboardShortcuts(enabled) {
    return $Call.ByID(248813052, enabled);
}

/**
 * SetLLMBaseURL saves the provider base URL.
 * Empty value resets to provider default endpoint behavior.
 * @param {string} baseURL
 * @returns {$CancellablePromise<void>}
 */
export function SetLLMBaseURL(baseURL) {
    return $Call.ByID(3179678031, baseURL);
}

/**
 * SetLLMMode saves the configured LLM operation mode.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetLLMMode(mode) {
    return $Call.ByID(1196399996, mode);
}

/**
 * SetLLMModel saves the configured LLM model.
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SetLLMModel(model) {
    return $Call.ByID(1381253168, model);
}

/**
 * SetLLMProvider saves the LLM provider.
 * @param {string} provider
 * @returns {$CancellablePromise<void>}
 */
export function SetLLMProvider(provider) {
    return $Call.ByID(4197289026, provider);
}

/**
 * SetLocalRuntimeEngine saves the configured local runtime engine.
 * @param {string} engine
 * @returns {$CancellablePromise<void>}
 */
export function SetLocalRuntimeEngine(engine) {
    return $Call.ByID(2832368751, engine);
}

/**
 * SetLocalRuntimeModel saves the configured local runtime model.
 * @param {string} model
 * @returns {$CancellablePromise<void>}
 */
export function SetLocalRuntimeModel(model) {
    return $Call.ByID(3098276198, model);
}

/**
 * SetOpenAIAPIKey saves the OpenAI API key.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetOpenAIAPIKey(key) {
    return $Call.ByID(2467546573, key);
}

/**
 * SetReedAPIKey saves the Reed API key and updates the adapter immediately.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetReedAPIKey(key) {
    return $Call.ByID(528752499, key);
}

/**
 * SetTheme saves the theme preference. Must be "dark", "light", or "system".
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(466396097, theme);
}

/**
 * StartLocalRuntime starts the configured local runtime and returns current status.
 * @returns {$CancellablePromise<localruntime$0.Snapshot>}
 */
export function StartLocalRuntime() {
    return $Call.ByID(3352722605).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * StopLocalRuntime stops the app-managed local runtime process and returns current status.
 * @returns {$CancellablePromise<localruntime$0.Snapshot>}
 */
export function StopLocalRuntime() {
    return $Call.ByID(2360813809).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = localruntime$0.ModelCatalog.createFrom;
const $$createType1 = localruntime$0.PullProgress.createFrom;
const $$createType2 = localruntime$0.Snapshot.createFrom;
const $$createType3 = localruntime$0.PullResult.createFrom;
